apiVersion: oidc.homelab.olav.ninja/v1alpha1
kind: XOidcClient
metadata:
  name: netbird-backend
spec:
  clientId: netbird-backend
  clientSecretSecretRef:
    name: netbird-backend-oidc-credentials
    namespace: netbird
    key: clientSecret
  description: Netbird Backend Client
  displayName: Netbird Backend
  type: CONFIDENTIAL
  grantTypes:
    - client_credentials
    - code
    - device_code
    - password
  redirectUris:
    - "/*"
  webOrigins:
    - "+"
  serviceAccountRoles:
    - realm: homelab
      client: builtin-homelab-realm-management
      role: view-users
  realm: homelab
