kind: Deployment
apiVersion: apps/v1
metadata:
  name: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    spec:
      volumes:
        - name: plex-config
          hostPath:
            path: "/mnt/sdb1/homelab/config/plex"
        - name: media-data
          hostPath:
            path: "/mnt/sdb1/data"
        #- name: plex-config-pv
        #  persistentVolumeClaim:
        #    claimName: plex-config
        #- name: media-data-pv
        #  persistentVolumeClaim:
        #    claimName: media-data
      containers:
        - name: plex
          image: lscr.io/linuxserver/plex
          volumeMounts:
            - mountPath: "/config"
              name: plex-config
            - mountPath: "/app/data"
              name: media-data
            #- mountPath: "/config"
            #  name: plex-config-pv
            #- mountPath: "/app/data"
            #  name: media-data-pv
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Oslo
          ports:
            - name: web
              containerPort: 32400
            - name: a
              containerPort: 1900
              protocol: UDP
            - name: b
              containerPort: 3005
            - name: c
              containerPort: 8324
            - name: d
              containerPort: 32410
              protocol: UDP
            - name: e
              containerPort: 32412
              protocol: UDP
            - name: f
              containerPort: 32413
              protocol: UDP
            - name: g
              containerPort: 32414
              protocol: UDP
            - name: h
              containerPort: 32469