apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plex
commonLabels:
  app: plex

resources:
  #  - pv.yaml
  #  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
