apiVersion: v1
kind: Service
metadata:
  name: adguard-dns-dhcp
  namespace: dns
  annotations:
    io.cilium/lb-ipam-ips: 172.20.10.153
  labels:
    bgp.cilium.io/advertise-service: default
    bgp.cilium.io/ip-pool: default
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  # https://kubernetes.io/docs/concepts/services-networking/cluster-ip-allocation/
  clusterIP: 10.96.0.12
  ports:
    - name: dns-tls
      port: 853
      protocol: TCP
    - name: dns-quic
      port: 853
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      protocol: UDP
    - name: dchp
      port: 67
      protocol: UDP
    - name: https
      port: 443
      protocol: TCP
  selector:
    app: adguard
