apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: first-pool
spec:
  blocks:
    - start: 192.168.1.200
      stop: 192.168.1.255
  serviceSelector:
    matchLabels:
      arp.cilium.io/ip-pool: default
