apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - announce.yaml
  - bgp-ip-pool.yaml
  - bgp-advertise-lb-services.yaml
  - bgp-peer-ucg-max-config.yaml
  - bgp-peer-ucg-max-password.yaml
  - bgp-cluster-config.yaml
  - dashboards/cilium.yaml
  - dashboards/cilium-operator.yaml

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io
    version: 1.18.3 # renovate: github-releases=cilium/cilium
    releaseName: "cilium"
    includeCRDs: true
    namespace: kube-system
    valuesFile: values.yaml
