apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: arr
spec:
  storageClassName: proxmox-csi
  volumeName: pv-sonarr-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4G
