# https://github.com/bitnami/charts/blob/main/bitnami/keycloak/values.yaml
auth:
  adminUser: admin
  existingSecret: keycloak-admin-password
  passwordSecretKey: password

production: true

nodeSelector:
  topology.kubernetes.io/zone: euclid

proxy: edge

ingress:
  enabled: false

postgresql:
  enabled: true
  auth:
    existingSecret: keycloak-db-credentials
  # https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
  primary:
    nodeAffinityPreset:
      type: hard
      key: topology.kubernetes.io/zone
      values: [ euclid ]
    persistence:
      enabled: true
      existingClaim: keycloak-db
