apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arr

commonLabels:
  app: traefik-forward-auth

resources:
  - service.yaml
  - deployment.yaml
  - middleware.yaml

configMapGenerator:
  - name: configs
    files:
      - configs/traefik-forward-auth.ini