apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - http-route.yaml
  - relay-secret.yaml
  - coturn-credentials.yaml
  - authelia-oidc-credentials.yaml
  - agent
  - dashboard
  - management
  - relay
  - signal
