apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: stonegarden
  namespace: stonegarden
spec:
  parentRefs:
    - name: stonegarden
      namespace: gateway
  hostnames:
    - "stonegarden.dev"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: stonegarden
          port: 3000