apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: arr
spec:
  storageClassName: proxmox-csi
  volumeName: pv-prowlarr-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
