apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homepage
  namespace: argocd
  labels:
    dev.stonegarden: application
spec:
  generators:
    - git:
        repoURL: https://github.com/vehagn/homelab
        revision: remodel
        directories:
          - path: k8s/apps/homepage/*
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        dev.stonegarden: application
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: homepage
      source:
        repoURL: https://github.com/vehagn/homelab
        targetRevision: remodel
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true