apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: proxmox-tls
  namespace: proxmox
spec:
  parentRefs:
    - name: tls-passthrough
      namespace: gateway
  hostnames:
    - "proxmox.stonegarden.dev"
  rules:
    - backendRefs:
        - name: proxmox
          port: 443
