apiVersion: v1
kind: Service
metadata:
  name: unbound
  namespace: dns
spec:
  type: ClusterIP
  clusterIP: 10.96.0.11
  ports:
    - name: dns
      port: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      protocol: UDP
  selector:
    app: unbound
