apiVersion: v1
kind: Service
metadata:
  name: unbound
  namespace: dns
  annotations:
    io.cilium/lb-ipam-ips: 172.20.10.150
  labels:
    bgp.cilium.io/advertise-service: default
    lb-ipam.cilium.io/ip-pool: default-bgp
spec:
  type: LoadBalancer
  # https://kubernetes.io/docs/concepts/services-networking/cluster-ip-allocation/
  clusterIP: 10.96.0.11
  ports:
    - name: dns
      port: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      protocol: UDP
  selector:
    app: unbound
