---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lldap-credentials
  namespace: authelia
spec:
  encryptedData:
    password: AgAWNkN1wi0QkI65MClfXSM0Ch2rpvKbi/PphRKctB/V9o/HoIgBKhd+VdLIATOXDQlvdjQP4zej8D/KOi5RJ3X0zK9Shg6lwxgF4cV2AeDt/CXjVUWBYQnux29ZRh2jYmt3MguIlXuAtbvqjxQfuMd1seV3GFTBD1sCgTy1hDCTiKwFgG5wNs6/bg09piUYuMSUyliF0i7KL1UIsvdWVtK6nrurOWnimi9ylTAusXp9XQmkX4Sp5WNE3k4s5qxBXaTlGimdYTIfsnCSDg1bRc9woT7bE/gK0bEsQQXHrvUHis14/NyznvLBBmrGNPEOP5QkgwJzkPRofFXQj0bBJvGZ3U8q4gMBbdMHP2OePbxwMUPktp6aW2RbPBw//o5EMteVuEA+85zs2BCp9jzMMHlcNuTA+gYqgtgf1HNL8Fuu+MjyQcO6D+r1Z5DXkpLlHCvgUgYRZww5dyYStprBgbR0fwjnxmxF/xLbl+9XaHNxDY24LqjqT6yfq1amjo1SLG7g0an/Pp2BLswHSvfqhJvZmk4H69gYQiG5yDFPxj9kFx78D8cHPaABjAR6eBInIUbgFJum5/iqdpOKBv+L3Z65rclWknNimme32eC7T3H8WHSs4Dgxt6nbDzOVplsds9GMKmwVe5/p7a4G1zHyVzqufssTiiWVH6tAIO706t5hb1PBdHrimHFEEeCDgdbs6CD16wDEVmR2PNDuXAOwFZx1fdpuNXXgLllnVRfU3F30/Q==
  template:
    metadata:
      name: lldap-credentials
      namespace: authelia
