---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smtp-credentials
  namespace: authelia
spec:
  encryptedData:
    password: AgCo5nXL6IAbZlOiPsWrwvvVBaVCc1L5814pMm5B7ZWkvAj+Mnzi291tpFQR+B0cWHTrEXVY037XlRX7RTq2yk6NzBAN3ExZT3oKwg8ziMMBw+W3fjLTzE50CDuEgBEsHVFP+3J0IvbO4zbu4cv8Us05OKRc7NixMAixQUcOjCy5uza62iup9htFfQ27dEq4I94ag8BQ6EMAmE//mg/T7eYzgcsQ2FbU2eUyknMHyZZyf7uw7+IZPTv0VHtR0lyTPCIJPPjcMCJzMhru+lJXaEFgU1iCaPrypr2GvJpdoqpDH6scNp6nI/UT9lhPKCGhiP464/VrjXjhmYNOQg2yMtnNZdMclUoVItN7zAXXiFly429IrTS1hh3vHZi22eyNQfOa36JA6PA/eUCUH4ql3kX13C1Qm35rc+Y3S1L3at1jnAswBbszLhaGXau6VmFbali1xwbrF68/hoe/OhaZo2E3h9Ay8YczXUzdRnNYP6QH0An725frl/DpoizpKQvWUAL9SjKndYK9EQm6lJXqtxcTSEgJlWsYea0nbBINQs8HZZi0qAG1BSRhS9VY92MmIG7sgtLW8xw1Gi6fJZtLVDLpinDyqJMJjG4/jvtILghCr3qvP+piIxm4rPs9gj+aY6ymUaGeV54jlBZTgAOIJB5dhiceGI67dLOn86HDwb8GJT/qYHO09r700s9uY45cIydpjM2Lv+vZ++EV2bp4uIXJU1cgTp3A9Qrs2AA+ukI18M8JO7ZC
    username: AgA9z9EZEuIj1kRYmE/oWATIrIiGUpR+UrIBPUcqMQg4/dRGGJwrSow8JUL2KnGAlpHSSUd0XQD3KE8Ndl9Ps2sCxgB9apW1mrv6XAG6xVyoMt1so5snOmONL7VnschLE7nsQHKd04M0GaBRDDdEt9sL3a1KotFB0cjmViCNGtHbl2vL+YXeEyG+1BawqZ16jxh0HAIRuoMAxozOJzy05pMLkpGeR9L1TPAp9xdncKPAr5jvjmF17T9UDJ8LbWItSua/cJ8oTBA+BzTxS3UQgg3pjR0ldvAeFd/kOJU/zk41xDtMkz0QharSP+7Bmp8uM87cdPq3SciT+IrvJirMr8yYMOynCteQx4sOQvn1/MojribK9mhZCCv4w7F/NZbetJTQprzA0W3m3m3vsB9q2UxAJPZnb+0ctRItS3pbbLqobU+7n36xdl8oKOK6+wcInnsoA+nsEKf6eVvazPYTNOgT9RZqjcdVJHVvaVba9B5FDRDj7b6ssMizTmbKdx0I4eZ4yLjqAM+91ewMPDaX0/SYbn95pq8ekGFRyObwb9CdnKJUqEe3sb77paMynLPqAlD8KIMvHUT/YE4SQNiiyIxg0gsFJamUmUfY8J0wkz2IdZHvWfZDs0sX5vMsXpsxM0Fdsta6804aoA+Ox43krYTvfb2xexJK/Az0egwOo19VJf+WBqwrXw0p/XX90NvUvyYlEgCFMX7k7FMNclM+Z5jLOt/Orl+w5+vY
  template:
    metadata:
      name: smtp-credentials
      namespace: authelia
