---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: valkey-credentials
  namespace: authelia
spec:
  encryptedData:
    password: AgBvXFkDHid089VXgZk08V9tjL7lA/N4LXSYZlRPxCucUICfbmpAXjsEuFOsAh+8jAfNQ1723pvd4G5Nv+5qaQC8CCucQ5G1+NuZAahxveCCHf7J/Bra8D7odvD2VsoyEJ0pSqzsHIHWMCZ1baeALehgREEqVPSFwbRrxI4jPfzSWTVUZkDDyWgt9Xi3XcyOstZioWAFB8ITTmyeTYVjXggwzgw9QB94HlvtL0JA+mHJ8seOPuuyzYlYV6G1WekFPTwaKA5WgX+htQxLye2EWzOP8ihzPJ8vu779DbrnAkc5zZVzPgA9mZw883jUkJbiKOKJLEm2p/2WMZNdiBzM9IJt/hX6ppBO9V5IZ1mRHbA5pePZrKbtjs0fbqwfic3ycM/fECIWAIEpVwTnpKBWWtvLsPmARUFmhLrrX+yqQAdYaGRmERh0vnDmLGv9ZyzdqzvgtPZixdkZ0kxV/JdIDhmZ2SxlfDr0wIERCotje0SdEqPxuG5+8VGDGGTk0nj32Uh59vzatAsGO1NFlmF4FiKf73PWzDgqWmKVxetRdl0mKdNgTURCriI6oeufih/Mb5jB+O4cU+SJ4OboD/qINQksK3REhylOWB3yJGCWAblQnFK5xD0gaTmDJlbImU0opX2Wxk3IhvAOdMWT+SetqJ2Pf+Z0CHxFyS5TtSn34KpF8F0nR+jhv/bdSL97vsgLNHs74mDeNmgxASadyWsS8f2a8wZyJnN7YxWzMYMjpu4Jx/2Row8=
  template:
    metadata:
      name: valkey-credentials
      namespace: authelia
