---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-argocd
  namespace: authelia
spec:
  encryptedData:
    clientSecret: AgAMZu3YM3yJNe0qAcZgGajD+NNKjHg/ofbHfgLJ51K/SZgcr0vcVw7dPgLcNv8AsoKK4G1J8SaBPxxQc2EoOE/FysN03qiaRQkiDZpl3Q/A8lbqtbCA5o+BwOrT2D5IHpY5keX7Lf/kOtw4VIgGah/p7E+PAzHh3VyngPlCPahiEeokpD0WA/lu1kLHpN/0xopiVElW2bWQTa9sPRd0R8cIxIJOi/xGw4MoaCN1A+aZBR5KQaXfBCOyI4R77vLwDe+HAXyQQwH82K+0YdD6Js6vGEsqSf5SDdmKiuy0/ztV9lf4sThKjKlQw1OAwLomlxRLVt+5BcrUWJCgUr8xVtneFwBe/wA9vEurKkIGJblrV8ewQpB974hXy9CGl1qGhB1hywbE/XsAAY2Wlxwa7utQKbwt/vUoKYpbAVk3GDMwfkrL/aOAAw3zXZF8bA21wiIQDEaiQO6dfIYjeZe6ispFfnQb6vdqxkTKW8LtHW6RXEpXgAulAaMKJIWzgpysEndE+0zUsjvl3AK9hmhTqL9t/F4NKz+17sgk9ko7WtN+ckNpQQinsX7ckuaM5iAOlR34bW/ZLgBDjQHv6HoqEMfYy2nWyeGVFuXHVxwbrYD5V2UPKQe3OxWze+9VvV0HSNG3Ghy5UL0jQTh8/ZABtz5fbDIqGrSat9WPElku0u25/BSBZGmk2ohipTNF6rM41YqaaXzcnxjLuybOlKwBElqIXLUzesd1Ue0h0j9n5AXLIUr5MaesWvDJt/r67IOgP9hsPPP9vSvjdZuutydOSWBZYXgZtfEiGKl00JVXdjN2yJWuGMLGb6JZFsP6XckltShehZsm3StyRW5myjWRLZU0r/qffiGeNFEu8l3FB8WoTnJZQg==
  template:
    metadata:
      name: client-argocd
      namespace: authelia
