---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-audiobookshelf
  namespace: authelia
spec:
  encryptedData:
    clientSecret: AgBQiUp4U3BY+le2rUGpLo3BUpLnuiD1Rz81rmq5jmz4KtRKDGhnlOKTgorFlFb/pu8LLmFIc3G/qr6yGk7QHN+w//SXT29clnaYVLm2zhgVGq0lUJSX+8JzhTu9xBXboQNON6PGSO63reCt6Pz1op2AqQABkdEgbDODKbMwZgWifhNGF539zgiDxdwpINp2KbvsVRe1QIJbyaqs4/WSGtwU7iTndjlWYRbW1evLjTGutnr2jbUOJtpASZwJ6DlUKMX7h0l70GJiqrDODV4WVhgJBNNq90pDvHkM6yuT5xquVsvndJdMZw606trelOmRRYYmM1p+iCR8KzqGSI4PN2xX10Fbr/4kUaN7jdskfSHcuexCVIxwfDd+MBJOl7KLf9ALnN7Rj60ZakpM2njfhHvgi7xB9T2sinjdhsBt/ovUDJ18HP5E1j43cDW944lI6e5KIO4i2pNqEVqM/bb6anGfO5dnuHtM/BI6H8auZZl5PAFPNrDDwQyg5oy/hA+OCCaxCqS0qYKbGqiyQ9vIrE5B8Oiun2T/IDUlpUB/xegevjROV3gzJp0+0OPEjloyB/5RPzZsKhY8vSet0blVFZJxq5PX1KxmR1n1q3ibhjZXS/DaLWbzJe5haqInzuJGjGjl+vMeMIYLzQgCZ4SQVc84CRZYJ4sf6gPAC9B/SSfY48RjDIwiKgnCFcJCvohqViJyeNeITpX7WhhXiQcRUA5qcj30XSrb/3Fc6m7uyHVvw2LaXSCcoCGtiEo1uoCajwfgMeGnHIMMWkHmtsUTSby7+9L/1lLHPZCBrcRfl9PnY3iExZ23HdBLKaGcWl6eJTH4iZ0clZkWmEh/HFqT2uP6aXGXOtyFkYJdKMNKWZiBALdF3A==
  template:
    metadata:
      name: client-audiobookshelf
      namespace: authelia
