---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-grafana
  namespace: authelia
spec:
  encryptedData:
    clientSecret: AgAgi3NGSP0t3KbPDbhO3IkBQcCtPLTqqFHN2ajI5D6KXTnvoAPaT87N5cMA6NZLPz0ZzCt3Vvdoe2D3jnz6x6IcqSOq9K8Z9ONNUQsSZreGS79LbHFVg6d+tjONdDnOumXTtjRhXImmBgcKgdlUMLxCaEex7N14KSyk+IxEkb56bEtfF52j52OMgtHFoe4RyVZ7vYKG+NSjityEYhUxfJ5bAaFNNeQaTSOtGKOggGIJQ5t8bLmxPS+0PxoE3SeKZRMWin5+v+ZDio8lJUVpUjprvlZrIZZuurSCybCuzR72+XlCE7LGiOlbX5iZFG/ZNvYhim2i6F4OufCDIJwnxcj6xwiU2mxtVVCus15VQM5UG8n9JiLM00ArJ1ZDwpTaMxyk/SnolIcx/4rwGA/xlTbxtjq7nvNVMwQbu335njDd4XmeQw7musHfKOE+GIIkASzRi3Gh26BK3DPeLiBMt5m+F/kyzkIWEMI8RANjKiFva/h4UvL4dWrGxRPJrOELekL3FcjM+T7APM5a/IdAvy/wOi7YWf3yNP6lHMHZiluntN+sMLZIe33ML0E7PVP4gLeU3G5BTSjRKYg23vOW6YKD0twcNqjt/Xfu2n8Yp+L2qNjxGnS0z+KQJfPCLYe/n2CYcWkNaeogkUGSdeY4UtFopHCjpBbXKBdqAeXlZfzZMmS6XLY72ugAAVVWoEvEcvt0ob22JXlNONpR9vTkOhjRAyRDKRyTMMephf0ri7qTNVkEGdYo8/c7EiuhKYoiD88Pad6bXvbdDEoADw7OhpfwQ3kNvCNSqeftU3tkCcJvlEPDn5a1AmrbrzMtwNsXhhK4abvJozphqntlmM44JpfKp8HOfF4Xmgw7d/KDMSarf43iQw==
  template:
    metadata:
      name: client-grafana
      namespace: authelia
