---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-netbird
  namespace: authelia
spec:
  encryptedData:
    clientSecret: AgCdaNF4FeFXPgC7wJomCDEabIqiNAo7NFIlux628i6NaGvu/3qyh4k2WXKLmUki+4pX+k4w/XOyz3ZM2tXI9GVmp+4cQkJIkf0sCzlC35tZpg2Le7hNxVKPv5waxnc+kbUppeA0yRQ5Yi4Pb9HQ61/Ji1t6Jh5CBwKOUzjBMUEO7Jv+0jCL2iy+RIFwQWv8y6BS/xvZukVSCJS0j6LXwFqD0v8trmpBbSMQzNkkFc90NfdXmIRx5zfkOHkgcBRB0rdg8YzuO/t9mVbMxv3h1Foy5a7eJ2s4v55k3DJKOPpB1iNufB+DzAoq9qdDm6bAHchfYzwwW75WYoUQZk71xeD1zPLEpWzW7KnZdB0hgLoe2faU9Jbz7nR/2Mr115C5Wycb0KV68QUGoYOCzsL1dXuFMzfh9LOCLivFBhHfIp2p/XERGdFUMYLd/ZHytdNaI8INwFzfLYH4K50ffCD3bfO9/sCSiv5CpBJqSR3rYmLp3QFHEreAA3xceWUTD5vf1ZKRGO7H8GAsKafXq5gYHAAE1wbJWaP6Zc1t+pEa9Kwdgkp59H1y3NYyBjXhV7iQiLPBqTjNUh5h9RM2DrkMJYDPeZYzhRoNFvFB61EEjTDpzVwBDrY772oPxP70TZQaBU5CH4HGsrLw1ZEF/UZ8gACPYX6K+jCWS76wskeZwwHG4JE0M0aHBPOk9bM+mpKRaUV5fsESxKXGZ0fITF8YFlVzIEiITmQ2Prde1P7dXElG6QgXIpY3VwjWdtIR8/p/Og2a8gkEo7UTPT4N62UXWSBQErXgU25DSeNY0zpQEdadLpG3RlrcQR/peZANNx8qVVMry2KuHWJ1vEMRqrgesBSL68c3cHLk41FrQkfWw03TpVL+Gg==
  template:
    metadata:
      name: client-netbird
      namespace: authelia
