apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: whoami
  labels:
    app: whoami
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      namespace: whoami
      labels:
        app: whoami
    spec:
      #affinity:
      #  nodeAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #      nodeSelectorTerms:
      #        - matchExpressions:
      #            - key: node-role.kubernetes.io/control-plane
      #              operator: DoesNotExist
      #securityContext:
      #  runAsNonRoot: true
      #  runAsUser: 999
      #  runAsGroup: 999
      #  fsGroup: 999
      #  fsGroupChangePolicy: OnRootMismatch
      #  seccompProfile:
      #    type: RuntimeDefault
      containers:
        - name: whoami
          image: ghcr.io/nicolaka/netshoot:v0.15
          command: [ /whoami/whoami ]
          #securityContext:
          #  allowPrivilegeEscalation: false
          #  readOnlyRootFilesystem: true
          #  capabilities:
          #    drop: [ ALL ]
          #    add: [ NET_ADMIN, NET_BIND_SERVICE, NET_RAW ]
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: whoami
              mountPath: /whoami
          resources:
            requests:
              cpu: 50m
              memory: 12Mi
            limits:
              cpu: 1000m
              memory: 24Mi
      volumes:
        - name: whoami
          image:
            reference: ghcr.io/traefik/whoami:latest
            pullPolicy: Always
